### ISSUE TITLE
The Bot State API is deprecated

### ISSUE THREAD

**Issue by Linaa** [aws-samples/amazon-lex-skype-integration#6]
2018-10-09T21:50:38.583Z	5c0088f8-cc0d-11e8-844f-29d10c0c134c	The Bot State API is deprecated. Please refer to https://aka.ms/I6swrh for details on how to replace with your own storage.
2018-10-09T21:50:39.142Z	5c0088f8-cc0d-11e8-844f-29d10c0c134c	Error: GET to 'https://state.botframework.com/v3/botstate/webchat/conversations/b88443f3b48547349c101a90405eacf9' failed: [405] Method Not Allowed
at Request._callback (/var/task/node_modules/botbuilder/lib/bots/ChatConnector.js:647:46)
at Request.self.callback (/var/task/node_modules/request/request.js:185:22)
at emitTwo (events.js:106:13)
at Request.emit (events.js:191:7)
at Request.<anonymous> (/var/task/node_modules/request/request.js:1161:10)
at emitOne (events.js:96:13)
at Request.emit (events.js:188:7)
at IncomingMessage.<anonymous> (/var/task/node_modules/request/request.js:1083:12)
at IncomingMessage.g (events.js:292:16)
at emitNone (events.js:91:20)

**Comment by kmangalorekar** [comment]
I have to same issue, any help would be appreciated!

**Comment by NikhilSingla-88** [comment]
I have the same issue, also I think need to used bot-azure. Anybody worked on that

**Comment by owolabiezekiel** [comment]
I found code online that added the storage to the connection like this

`var bot = new builder.UniversalBot(connector, {
    storage: new builder.MemoryBotStorage()
});`

**Comment by ttn-aditya** [comment]
I am still facing this issue.Can you share a sample where to put this piece of code and the additional AWS or Azure service required to fix this issue @owolabiezekiel

**Comment by ttn-aditya** [comment]
Does this sample integration works for Microsoft Teams as well?
If not is there a way to integrate AWS Lex and Microsoft Teams?
